//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess
{
    
    #region Windows Form Designer generated code
    public partial class Form1
    {
        private void InitializeComponent()
        {
            this.LocalGameBtn = new System.Windows.Forms.Button();
            this.SettingsBtn = new System.Windows.Forms.Button();
            // 
            // LocalGameBtn
            // 
            this.LocalGameBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.LocalGameBtn.Text = "New Game";
            this.LocalGameBtn.UseVisualStyleBackColor = true;
            this.LocalGameBtn.Location = new System.Drawing.Point(61, 17);
            this.LocalGameBtn.Name = "LocalGameBtn";
            this.LocalGameBtn.Size = new System.Drawing.Size(102, 28);
            this.LocalGameBtn.TabIndex = 0;
            this.LocalGameBtn.Click += new System.EventHandler(this.LocalGameBtn_Click);
            // 
            // SettingsBtn
            // 
            this.SettingsBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.SettingsBtn.Text = "Settings";
            this.SettingsBtn.UseVisualStyleBackColor = true;
            this.SettingsBtn.Location = new System.Drawing.Point(61, 81);
            this.SettingsBtn.Name = "SettingsBtn";
            this.SettingsBtn.Size = new System.Drawing.Size(102, 28);
            this.SettingsBtn.TabIndex = 2;
            this.SettingsBtn.Click += new System.EventHandler(this.SettingsBtn_Click);
            // 
            // Form1
            // 
            this.ClientSize = new System.Drawing.Size(219, 145);
            this.Text = "Form1";
            this.Controls.Add(this.SettingsBtn);
            this.Controls.Add(this.LocalGameBtn);
            this.Name = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
        }
        private System.Windows.Forms.Button LocalGameBtn;
        private System.Windows.Forms.Button SettingsBtn;
    }
    #endregion
}
