//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess
{
    
    #region Windows Form Designer generated code
    public partial class SettingsEditForm
    {
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.PiesSizeTextBox = new System.Windows.Forms.TextBox();
            this.MarginToTopTextBox = new System.Windows.Forms.TextBox();
            this.MarginToLeftTextBox = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.WhiteCellColorBtn = new System.Windows.Forms.Button();
            this.BlackCellColorBtn = new System.Windows.Forms.Button();
            this.MoveOptionColorBtn = new System.Windows.Forms.Button();
            this.EatOptionColorBtn = new System.Windows.Forms.Button();
            this.HighlightedCellColorBtn = new System.Windows.Forms.Button();
            this.ExportBtn = new System.Windows.Forms.Button();
            this.SaveBtn = new System.Windows.Forms.Button();
            this.ImportBtn = new System.Windows.Forms.Button();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Image = null;
            this.label1.Text = "Selected Highlight:";
            this.label1.Location = new System.Drawing.Point(48, 352);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(101, 16);
            this.label1.TabIndex = 0;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Image = null;
            this.label2.Text = "Margin to top";
            this.label2.Location = new System.Drawing.Point(48, 96);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(76, 16);
            this.label2.TabIndex = 0;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Image = null;
            this.label3.Text = "Pies Size:";
            this.label3.Location = new System.Drawing.Point(48, 40);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(50, 16);
            this.label3.TabIndex = 0;
            // 
            // PiesSizeTextBox
            // 
            this.PiesSizeTextBox.Text = "";
            this.PiesSizeTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.PiesSizeTextBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PiesSizeTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.PiesSizeTextBox.MaxLength = 3;
            this.PiesSizeTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PiesSizeTextBox.Location = new System.Drawing.Point(152, 40);
            this.PiesSizeTextBox.Name = "PiesSizeTextBox";
            this.PiesSizeTextBox.Size = new System.Drawing.Size(72, 22);
            this.PiesSizeTextBox.TabIndex = 1;
            // 
            // MarginToTopTextBox
            // 
            this.MarginToTopTextBox.Text = "";
            this.MarginToTopTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.MarginToTopTextBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.MarginToTopTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.MarginToTopTextBox.MaxLength = 3;
            this.MarginToTopTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MarginToTopTextBox.Location = new System.Drawing.Point(152, 96);
            this.MarginToTopTextBox.Name = "MarginToTopTextBox";
            this.MarginToTopTextBox.Size = new System.Drawing.Size(72, 22);
            this.MarginToTopTextBox.TabIndex = 1;
            this.MarginToTopTextBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.IgnoreNotNumeric);
            // 
            // MarginToLeftTextBox
            // 
            this.MarginToLeftTextBox.Text = "";
            this.MarginToLeftTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.MarginToLeftTextBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.MarginToLeftTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.MarginToLeftTextBox.MaxLength = 3;
            this.MarginToLeftTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MarginToLeftTextBox.Location = new System.Drawing.Point(152, 144);
            this.MarginToLeftTextBox.Name = "MarginToLeftTextBox";
            this.MarginToLeftTextBox.Size = new System.Drawing.Size(72, 22);
            this.MarginToLeftTextBox.TabIndex = 1;
            this.MarginToLeftTextBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.IgnoreNotNumeric);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Image = null;
            this.label4.Text = "Margin To Left";
            this.label4.Location = new System.Drawing.Point(48, 144);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(80, 16);
            this.label4.TabIndex = 0;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Image = null;
            this.label5.Text = "White Cell Color:";
            this.label5.Location = new System.Drawing.Point(48, 192);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(90, 16);
            this.label5.TabIndex = 0;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Image = null;
            this.label6.Text = "Black Cell Color:";
            this.label6.Location = new System.Drawing.Point(48, 232);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(87, 16);
            this.label6.TabIndex = 0;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Image = null;
            this.label7.Text = "Move Option Color";
            this.label7.Location = new System.Drawing.Point(48, 272);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(104, 16);
            this.label7.TabIndex = 0;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Image = null;
            this.label8.Text = "Eat Option Color";
            this.label8.Location = new System.Drawing.Point(48, 312);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(91, 16);
            this.label8.TabIndex = 0;
            // 
            // WhiteCellColorBtn
            // 
            this.WhiteCellColorBtn.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            this.WhiteCellColorBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.WhiteCellColorBtn.Text = "";
            this.WhiteCellColorBtn.UseVisualStyleBackColor = true;
            this.WhiteCellColorBtn.Location = new System.Drawing.Point(160, 192);
            this.WhiteCellColorBtn.Name = "WhiteCellColorBtn";
            this.WhiteCellColorBtn.Size = new System.Drawing.Size(26, 25);
            this.WhiteCellColorBtn.TabIndex = 2;
            this.WhiteCellColorBtn.Click += new System.EventHandler(this.PickColorBtn_Click);
            // 
            // BlackCellColorBtn
            // 
            this.BlackCellColorBtn.BackColor = System.Drawing.Color.Green;
            this.BlackCellColorBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.BlackCellColorBtn.Text = "";
            this.BlackCellColorBtn.UseVisualStyleBackColor = true;
            this.BlackCellColorBtn.Location = new System.Drawing.Point(160, 232);
            this.BlackCellColorBtn.Name = "BlackCellColorBtn";
            this.BlackCellColorBtn.Size = new System.Drawing.Size(26, 25);
            this.BlackCellColorBtn.TabIndex = 2;
            this.BlackCellColorBtn.Click += new System.EventHandler(this.PickColorBtn_Click);
            // 
            // MoveOptionColorBtn
            // 
            this.MoveOptionColorBtn.BackColor = System.Drawing.Color.Cyan;
            this.MoveOptionColorBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.MoveOptionColorBtn.Text = "";
            this.MoveOptionColorBtn.UseVisualStyleBackColor = true;
            this.MoveOptionColorBtn.Location = new System.Drawing.Point(160, 272);
            this.MoveOptionColorBtn.Name = "MoveOptionColorBtn";
            this.MoveOptionColorBtn.Size = new System.Drawing.Size(26, 25);
            this.MoveOptionColorBtn.TabIndex = 2;
            this.MoveOptionColorBtn.Click += new System.EventHandler(this.PickColorBtn_Click);
            // 
            // EatOptionColorBtn
            // 
            this.EatOptionColorBtn.BackColor = System.Drawing.Color.Gold;
            this.EatOptionColorBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.EatOptionColorBtn.Text = "";
            this.EatOptionColorBtn.UseVisualStyleBackColor = true;
            this.EatOptionColorBtn.Location = new System.Drawing.Point(160, 312);
            this.EatOptionColorBtn.Name = "EatOptionColorBtn";
            this.EatOptionColorBtn.Size = new System.Drawing.Size(26, 25);
            this.EatOptionColorBtn.TabIndex = 2;
            this.EatOptionColorBtn.Click += new System.EventHandler(this.PickColorBtn_Click);
            // 
            // HighlightedCellColorBtn
            // 
            this.HighlightedCellColorBtn.BackColor = System.Drawing.Color.DimGray;
            this.HighlightedCellColorBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.HighlightedCellColorBtn.Text = "";
            this.HighlightedCellColorBtn.UseVisualStyleBackColor = true;
            this.HighlightedCellColorBtn.Location = new System.Drawing.Point(160, 353);
            this.HighlightedCellColorBtn.Name = "HighlightedCellColorBtn";
            this.HighlightedCellColorBtn.Size = new System.Drawing.Size(26, 25);
            this.HighlightedCellColorBtn.TabIndex = 2;
            this.HighlightedCellColorBtn.Click += new System.EventHandler(this.PickColorBtn_Click);
            // 
            // ExportBtn
            // 
            this.ExportBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.ExportBtn.Text = "Export";
            this.ExportBtn.UseVisualStyleBackColor = true;
            this.ExportBtn.Location = new System.Drawing.Point(280, 120);
            this.ExportBtn.Name = "button1";
            this.ExportBtn.Size = new System.Drawing.Size(72, 30);
            this.ExportBtn.TabIndex = 3;
            this.ExportBtn.Click += new System.EventHandler(this.ExportBtn_Click);
            // 
            // SaveBtn
            // 
            this.SaveBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.SaveBtn.Text = "Save";
            this.SaveBtn.UseVisualStyleBackColor = true;
            this.SaveBtn.Location = new System.Drawing.Point(280, 320);
            this.SaveBtn.Name = "button2";
            this.SaveBtn.Size = new System.Drawing.Size(72, 30);
            this.SaveBtn.TabIndex = 3;
            this.SaveBtn.Click += new System.EventHandler(this.SaveBtn_Click);
            // 
            // ImportBtn
            // 
            this.ImportBtn.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.ImportBtn.Text = "Import";
            this.ImportBtn.UseVisualStyleBackColor = true;
            this.ImportBtn.Location = new System.Drawing.Point(280, 56);
            this.ImportBtn.Name = "button3";
            this.ImportBtn.Size = new System.Drawing.Size(72, 30);
            this.ImportBtn.TabIndex = 3;
            this.ImportBtn.Click += new System.EventHandler(this.ImportBtn_Click);
            // 
            // SettingsEditForm
            // 
            this.ClientSize = new System.Drawing.Size(389, 395);
            this.Text = "SettingsEditForm";
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.PiesSizeTextBox);
            this.Controls.Add(this.MarginToTopTextBox);
            this.Controls.Add(this.MarginToLeftTextBox);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.WhiteCellColorBtn);
            this.Controls.Add(this.BlackCellColorBtn);
            this.Controls.Add(this.MoveOptionColorBtn);
            this.Controls.Add(this.EatOptionColorBtn);
            this.Controls.Add(this.HighlightedCellColorBtn);
            this.Controls.Add(this.ExportBtn);
            this.Controls.Add(this.SaveBtn);
            this.Controls.Add(this.ImportBtn);
            this.Name = "SettingsEditForm";
            this.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.IgnoreNotNumeric);
        }
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox PiesSizeTextBox;
        private System.Windows.Forms.TextBox MarginToTopTextBox;
        private System.Windows.Forms.TextBox MarginToLeftTextBox;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Button WhiteCellColorBtn;
        private System.Windows.Forms.Button BlackCellColorBtn;
        private System.Windows.Forms.Button MoveOptionColorBtn;
        private System.Windows.Forms.Button EatOptionColorBtn;
        private System.Windows.Forms.Button HighlightedCellColorBtn;
        private System.Windows.Forms.Button ExportBtn;
        private System.Windows.Forms.Button SaveBtn;
        private System.Windows.Forms.Button ImportBtn;
    }
    #endregion
}
